#!/bin/sh

set -e
umask 0002

OPTIONS="--polar disabled"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if test -f "disabled.bin"; then
    /usr/bin/sudo /usr/bin/systemctl --quiet disable rspamd.service
    if systemctl is-active --quiet rspamd-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop rspamd.service
    else
      echo "antispam will be disabled on next reboot."
    fi
  else
    /usr/bin/sudo /usr/bin/systemctl --quiet enable rspamd.service
    if systemctl is-active --quiet rspamd-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart rspamd-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart rspamd.service
    else
      echo "antispam will be enabled on next reboot."
    fi
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

